### PR TITLE
Remove gauge from README.

### PR DESCRIPTION
**Pull request by satazor**

### CODE REVIEW

**Comment by gillesdemey** [comment]
:+1: LGTM!

**Comment by satazor** [comment]
@gillesdemey I ended up choosing your module instead of `gauge` because of a discussion in a gauge issue. Perhaps we should add to the README the advantages of using this module instead of gauge.

Also, would you consider bumping this to 1.0.0 stable?

Thanks

**Comment by gillesdemey** [comment]
I'll bump the version to 1.0.0, but the intention is to implement some of the ideas here in Gauge — providing a nice and consistent loader for every platform.

**Comment by satazor** [comment]
I see! I will be using your module but I will keep an eye at gauge. Thanks for you work!

**Pull request merged**
